name: checkout-actions
on: [push]

jobs:
  Checkout-Action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Befor
        run: ls -a
      - name: using-actions
        uses: actions/checkout@v3
      - name: List Files After
        run: ls -a
      
