name: expression-and-context
on: [push, pull_request, issues, workflow_dispatch]

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ "This is a string" }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' = 'string' }}
          echo ${{ true && false }} 
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          

