name: expression-and-context
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Epression & contest by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  runs-on-issues-and-prs:
    runs-on: ubuntu-latest
    if: contains(fromJson('["pull_request, "issues"]'), github.event_name)
    steps:
      - name: Run only if issue have a bug labes
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
          echo ${{ join(github.event.issue.labels.*.name, ', ') }}

  expressions:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'string' }}
          echo ${{ true && false }} 
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          

