name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Ali"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: pilotgab/captaingab/.github/workflows/reusable-workflow.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
