name: shell command & workingdir
on: [push]


jobs:

  shell_coomand_working-dir:
    runs-on: ubuntu-latest
    steps:
      - name: present working dir
        run: pwd
      - name: list all content in pwd
        run: |
          ls 
          ls -a
      - name: permistion on the files
        run: ls -l

      - name: github workspace
        run: |
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY 
          echo $GITHUB_SHA