name: workflow-run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
jobs:
  echo-strig:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I actually waited for the repository event to be completed before I was triggerd"